### ISSUE TITLE
Help in understanding the problem

### ISSUE THREAD

**Issue by pallavijog13** [cladius/solution#21]
In Girlfriend problem ([2021/SemiFinal/2](https://github.com/cladius/solution/tree/master/2021/SemiFinal/2)), isnt the solution already provided in the input data itself?
Since final road approaching destination house is given the total cost in the input data itself, we just need to find out the final roads approaching destination house and get the minimum value as the lowest cost.

E.g.  in the given example - 2-5 cost is 40 and 4-5 cost is 30. So the answer is 30. Isn't it? Or am I missing something?

```
5 5
1 2 30
1 3 10
2 5 40
3 4 20
4 5 30
```

**Comment by cladius** [comment]
**You are partially correct @pallavijog13.**

I solved it in a very indirect (and unnecessarily complex) method. There were others who were wiser than me who took the easier (and more elegant) approach mentioned by you. However, you need to consider 2 edge cases to complete the solution.

## Not reachable
The guy might not be able to reach her house via any path, despite there being roads leading to the last house.

## Least incoming road
The guy might not be able to reach her house via the incoming road on the last node with the least cost. Hence, we cannot simply list down the incoming roads on the last node and select that as a winner.

I hope this provides clarification.

**Comment by pallavijog13** [comment]
Thanks @cladius .
I got your 1st point.
However, not sure about 2nd one. Can you give some example?
As I thought that last path cost is always cumulative sum of all the connected road costs. So, if H1 is connected to H5, then its always cumulative sum right from H1 and H5.

**Comment by cladius** [comment]
@pallavijog13  pls consider this example

<img width="506" alt="image" src="https://user-images.githubusercontent.com/11571484/202676770-1d11a52d-2444-4d84-beb8-aa2aff3d1007.png">

There are 2 incoming roads on the last node. However, the least cost option cannot be chosen as the correct answer. Since it doesn't help the first node to traverse till the final node.

**Comment by pallavijog13** [comment]
Yes. Thanks!

I have taken into consideration this thing in my solution. Please accept my Python solution.
I am comparing only valid paths from source to destination and selecting shortest among 2.

Also, added python solution for Agniveer problem.

**Comment by cladius** [comment]
Thanks. Done.
